### ISSUE TITLE
HTML5: localStorage is not available under some conditions

### ISSUE THREAD

**Issue by aglitchman** [subsoap/defsave#12]
`localStorage` and `sessionStorage` are not available when game runs in Google Chrome + Private (Incognito Mode) + IFrame. So, DefSave crashes with the error:

```
defsave.defsave:128: SecurityError: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
stack traceback:
  [C]:-1: in function run
  defsave.defsave:128: in function load
...
```

I think that DefSave should silently ignore storing/loading the save data under these conditions.

**Comment by subsoap** [comment]
Does it happen in Firefox private mode too?

Will need to detect incognito / private mode

https://stackoverflow.com/questions/2860879/detecting-if-a-browser-is-using-private-browsing-mode

Detecting iframe is easy 

> html5.run("self === top")

**Comment by subsoap** [comment]
It seems Google actively works to prevent Incognito mode detection. I can't find a method that works.

A solution may be to wrap the sys.save in a pcall and try to detect error that way.

**Comment by aglitchman** [comment]
Yes. Or wrap it into JS try-catch:
```lua
-- load...
loaded_file = json.decode(html5.run([[(function(){try{return window.localStorage.getItem(']] .. path .. [[')||'{}'}catch(e){return'{}'}})()]]))

-- store...
html5.run([[try{window.localStorage.setItem(']] .. path .. [[', ']] .. encoded_data .. [[')}catch(e){}]])
```

**Comment by subsoap** [comment]
I will test try-catch.

**Comment by subsoap** [comment]
Seems to not crash
![2021-02-09 02_07_02-HTTPS iframe test - JSFiddle - Code Playground](https://user-images.githubusercontent.com/409170/107348183-8fbd4680-6a7b-11eb-95ef-f682f14ccca3.png)

Did you already test? Here is a branch with it set, can you confirm if this works for you?

https://github.com/subsoap/defsave/archive/html5-try-catch-localstorage.zip

**Comment by subsoap** [comment]
I tested Version 88.0.4324.150 of Chrome with the older version and did not see it crash the same way you did before when testing game in an iframe on a different server in private mode. Maybe the example project is not sufficient in making it crash? You'll need to test and see what works for now.

If you can please share a sample of the <iframe tag you are using.

**Comment by aglitchman** [comment]
I tested the fix, and yes, it works. You can also add `console.log(e);` right after `catch(e){` to be sure that it works.

The error happens on Yandex Games portal because they wrap games into an iframe. I'll try to make a sample to reproduce the issue.

**Comment by subsoap** [comment]
Since you say it works I published a new release https://github.com/subsoap/defsave/releases/tag/v1.2.2

If you want other changes related to this please do a pull request.
