### ISSUE TITLE
deserialization of boolean not work

### ISSUE THREAD

**Issue by Vbif** [subsoap/defsave#14]
I have noticed that in some cases boolean values serialize with first capital letter, and then failed to deserialize. Probably can be fixed with encode function like this

> local function encode_boolean(val)
>   return string.lower(tostring(val))
> end

**Comment by subsoap** [comment]
This may be a bug with Defold's sys.save / sys.load since that's what DefSave uses for this, you should report it here https://github.com/defold/defold
