### ISSUE TITLE
Typos in code (warnings)

### ISSUE THREAD

**Issue by e1e5en-gd** [subsoap/defsave#17]
VS Code gives the following warnings
![image](https://user-images.githubusercontent.com/7114353/151345731-4a07f94e-03b9-43ef-b462-df2bbf0a97d7.png)

**Comment by subsoap** [comment]
https://github.com/subsoap/defsave/blob/master/defsave/profile.lua#L58

This one is a good catch. Do a pull request to fix it?

The UUID stuff idk. It should probably be removed.
