### ISSUE TITLE
clear all saves

### ISSUE THREAD

**Issue by TinyDobbins** [subsoap/defsave#4]
add please method to remove all saves, for example to add the opportunity to clear progress of the game.

now for example there is only way via:
```
defsave.set("config", "value1", nil)
defsave.save("config")
```

**Comment by subsoap** [comment]
defsave.reset_to_default("config") not work how you want?

**Comment by TinyDobbins** [comment]
thanks @subsoap ! no found it in docs, but just checked in source. yes, that's what I need.

**Comment by subsoap** [comment]
Yeah, I need to write proper docs!
